name: programming
description: "General programming / dev-tools search"

searx_categories:
  - it
  - general

engines:
  - stackoverflow
  - github
  - codeberg
  - google
  - bing
  - duckduckgo

prefer_sites:
  - github.com
  - stackoverflow.com
  - man7.org
  - docs.python.org

blacklist:
  - pinterest.com
  - quora.com
  - w3schools.com
